<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Crystal/Crystal/Crystal.csproj" />
        <ProjectReference Include="../../Crystal/Crystal.Tools/Crystal.Tools.csproj" />
        <ProjectReference Include="../../Crystal/Crystal.Agents/Crystal.Agents.csproj" />
        <ProjectReference Include="../../Crystal/Crystal.Harness/Crystal.Harness.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
        <PackageReference Include="System.Text.Json" Version="10.0.11" />
    </ItemGroup>

</Project>
